### ISSUE TITLE
Shifted footnotes on PEP 595 

### ISSUE THREAD

**Issue by JulienPalard** [python/peps#1098]
Looks like footnotes are shifted on PEP 595:

> This concern has been raised in the past in a Zulip topic [19].

[...]

>  [19] The New-bugs-announce mailing list

**Comment by gvanrossum** [comment]
You're right, they're out of sync. Probably something in the doc confuses the code that numbers footnotes? (Personally I don't like bottom-notes -- I prefer inline URLs. But that's a separate battle.)

**Comment by hugovk** [comment]
Please see PR https://github.com/python/peps/pull/2534 to fix this.

**Comment by CAM-Gerlach** [comment]
There's actually quite a few instances of that throughout older PEPs; a lot of the ≈250 Sphinx warnings relate (ultimately) to misaligned footnote numbering. It wouldn't have been an issue if authors just used named/auto-numbered footnotes instead of hardcoded numbers, but until I updated it recently, PEP 12 described both methods and lacked a clear recommendation (now it only specifies auto-numbered footnotes, in cases where footnotes and not direct links are actually required).
