### ISSUE TITLE
The page becomes wider than the viewport on certain PEPs

### ISSUE THREAD

**Issue by pradyunsg** [python/peps#2476]
See https://peps.python.org/pep-0440/

The PEP is presented wider than other PEPs are presented, which makes the contents of this PEP more difficult to read.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting! The problem is due to the literal block in [this section](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions) that has an extremely long `<span>`s (i.e. the regex that has no breaks and is syntax-highlighted text with the same color).

To make a long story short, after some investigation and testing, setting an appropriately-bounded `max-width` on the page content for the widest breakpoint (where it was previously unbounded) avoided this problem and ensured the page displayed identically to other PEPs with more typical content, while not affecting anything else.

I opened PR #2478 with the solution.
