### ISSUE TITLE
pep-0020 missing space

### ISSUE THREAD

**Issue by BombasterMax** [python/peps#3105]
Missed space in 36 string before double hyphen

**Comment by hugovk** [comment]
Presumably you're talking about line 36:

https://github.com/python/peps/blob/cd7decdffa54e4b30ca7a1bc4938dcab492a536e/pep-0020.txt#L36

This is an intentional. The author Tim Peters said (https://github.com/python/cpython/issues/47614#issuecomment-1093430153):

> I'm afraid you missed the joke ;-) While you believe spaces are
required on both sides of an em dash, there is no consensus on this
point. For example, most (but not all) American authorities say /no/
spaces should be used. That's the joke. In writing a line about "only
one way to do it", I used a device (em dash) for which at least two ways
to do it (with spaces, without spaces) are commonly used, neither of
which is obvious -- and deliberately picked a third way just to rub it in.
> 
> This will never change ;-)

**Comment by encukou** [comment]
The real joke is that the joke is not obvious at first, unless you're American.
