### ISSUE TITLE
Removing myself as a PEP editor

### ISSUE THREAD

**Issue by brettcannon** [python/peps#3600]
I'm trying to prioritize my notifications and I realize my PEP editor notifications I consistently ignore/overlook. As such, I am removing myself from https://github.com/orgs/python/teams/pep-editors and dropping my admin access on the repo.

This is just an FYI and can be closed whenever (just didn't think of a better way to reach fellow editors).

**Comment by CAM-Gerlach** [comment]
Thank you for letting us know @brettcannon , and for your many years of service, and I'm glad you're taking care of yourself and prioritizing appropriately!

I haven't been that active recently myself as I've been mostly focused on my (funded) work with the Spyder project so I can keep the kitties fed, but I hope to get back to at least a reasonable level of activity soon.

Since it's been about two weeks and this will still show up in the notifications of subscribers (e.g. PEP editors)  regardless of open-close status, I guess I'll go ahead and mark this closed, since I don't believe there's anything more to be done here. Cheers!
