### ISSUE TITLE
Mention that post-history includes postings to python-ideas

### ISSUE THREAD

**Issue by Mariatta** [python/peps#440]
Should update the wording in PEP 1 and PEP 12.

https://mail.python.org/pipermail/python-dev/2017-October/149990.html

**Comment by njsmith** [comment]
There are also PEPs that get posted to other lists (e.g. ones with `Discussions-To: distutils-sig@...`), and I've always assumed that such posts should also go in the `Post-History` list.

While we're talking about it, I'm kind of puzzled about what the purpose of the `Post-History` header even is. It certainly doesn't make it very convenient to find the discussions later, especially when you don't even know what mailing list you should be looking at, and maintaining it can end up feeling like pointless make-work. A list of URLs pointing to the actual posts in the archives would be much more useful IMO.

**Comment by warsaw** [comment]
As I followed up on python-dev, `Post-History` deliberately mentions `python-dev` and `python-list` because those are the "forums of record".  As @njsmith rightly notes, there are lots of places that PEPs can be discussed and fleshed out, but the forums of record are the only places people *have* to read if they want to be informed of PEP status.

So I think `Post-History` should remain the dates on which a PEP is posted on `python-dev` and `python-list` only.  Perhaps the wording or rationale in PEP 1 and 12 need to be updated, but that's the background on the header.

**Comment by njsmith** [comment]
@warsaw IIUC the purpose of the `Discussions-To` header is to name an alternative forum-of-record (in particular, packaging related PEPs are often approved without ever seeing python-dev; there's a standing BDFL delegation and stuff). Also, I'm pretty sure that for other PEPs, only python-dev posting is mandatory -- you can't just post on python-list and be done, right? I actually wasn't aware that PEPs were ever posted to python-list -- the default these days is to do a few rounds of discussion on python-ideas and then move to python-dev, right?

Regarding the side-discussion about purpose of Post-History, are you saying that it's primary purpose is to serve as a statement that the PEP has in fact followed the rules and been posted to python-dev, and thus is potentially eligible for acceptance? That doesn't seem to be how it's used currently in my experience, but I could be wrong...

**Comment by Mariatta** [comment]
Thanks @warsaw and @njsmith.
I agree with what @njsmith said, having a link back to the actual post is useful.
What does one need to do to propose that such link be added to PEPs?
